### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [aryawinterfell/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by aryawinterfell** [comment]
Hi Ken,
Sorry I'm just getting to this! I added this meta tag in the <head>, <meta name="viewport" content="initial-scale=1"> Seems to look better on my phone as well as a smaller browser. Let me know if that's okay, thank you!!

**Comment by kenmazaika** [comment]
:+1: Thumbs up.  Looks great!
